package com.jicent.jetrun;

public class Constants {

	public static String[] receiveAddress = {"AMvxYtssRzgmFMztscntD6Puh4UMFS9AA",
			"AKjsV4BrWPV95gTQ6dkQbKgHPLUQaDd8p4",
			"A2zqbJGJ2VXm2CUYSz5ic2uqWuG7qTrKVq",
			"ADz8fn8ohozRVb9bcThZmChkC5DxhZqiFR",
			"ADsuuFv8JG8V4BoME4J1AeTvqcvzi64xi5",
			"AD9hb3jgzSuhTSJYWshry5gg1TUFSZs6Sf",
			"AAdPwktRftpeGPcU9AwSkt2bRjggBa8yTS",
			"A9nhZwBjez7bwHNNyrfnVDhczDEXzhYcUz",
			"AGVWUG5DQguF9e7ootF9Sd8NK2Zr6W4mWU",
			"AE4sBSgajPTt4DkxSjQ4FsLJq1wRvP6GP8",
			"APeGUS91MXig7mfXYQR3ULTDYxRj4demPk",
			"A2UtkUgkjypiJSSP2k1zBJH11ZYp5XLRHa",
			"ABc1y6GUBGkQBucoUwrFtCjzxFBXjBdzfn",
			"AJ5aEhXsdzXpDuaq9PXZuwWyysfteTtQN3",
			"ANqVAyJEdoUGvjmkpiwf4iyjvkvhrDPTYF",
			"AMjmtXuk7KC8ZfbxPuUCWRw9nBFJetrwV",
			"A6nyEEH7F13qBiYRmLQfhk2Ntwyn4s6tHT",
			"A281ruEv9Ej2wutfiZqFBMDE2VRawT5KQH",
			"ACrifQZ1sCuLkEj4xfZnFSS31gULGUSgJE",
			"ADjohnhMvfQPW4euMc7ecfFDj2QWUqVRKu",
			"AM1fzgaVbfX89JfdK1v8YsFehB3iNgqJY2",
			"A74zLkkvKF32apN28qK3sgdidZSoFykaQv",
			"ACEjKqwDnzMmQ3hkk1h6BiD8T1KWqTPfjy",
			"A272D3ko9adtywyccvPyfVtSuFK3d4kcxg",
			"A4cCxZbArj6ex1rt1wc2DdnqYu2373W3fq",
			"AF8auUDzX36fpYLFCTjJZE3CojzpMgVVns",
			"AH9EPA4iKEd6cMrXazFHaCVrkiFPKsLCu2",
			"AQC29uBqK876oa348iq5D55daDRBtfEcbz",
			"ADgZedUjZs6NDvbvoQ45rLYi673i8JSteL",
			"AETfixe2GXLQK8ZPkAJeanFidWmfdcSE2W",
			"A3NtkbNhKmSzdtxsMEjSjXbTnxA4HFKPZo",
			"A9fRQMV9gdrYUcac7M6JnbLz94QxyFYnrg",
			"A2EfMmvzatjmeQuLvagK54broowPi3dszQ",
			"ACwghwF8fPZ4vaxX3hnfKs5HoYthdfXJ8b",
			"AC4LcQCVUGjgmscaDexAjPprGvZXRzgjX7",
			"AAwiAKhzQTF7cNWqwD6AgQSDD3Sf3qBQgB",
			"AvTzx5gYe69acSM2r1TNhJTiauRUuiMrC",
			"AMVbLeq1NMbrP3uZjFoehaNV4psgMgDmCi",
			"ABogwB1y5reAMjGYRUGp3tMgMXmEtCbHH",
			"A7dzkGPqWU9Re1TYGqxnRFrsPu4ZQSpGU2",
			"AP13oWQRLozjAuzMyk11jQT28WLyBWkJtc",
			"A4nYKKBANYTUtF1EyYQuQFRz29oaZaCZVm",
			"AGcArFwyeCvR8cFXcx8Muonmzy7HuQnEyw",
			"AGQqdSf5dkeszgieTJmXicnTGGcPct2Tem",
			"A72QMFupqmM3xwbKzyw1X7CfiJC52AeicE",
			"AC4ZidSnbMwBRVhBH1QkHS1nuaF9YYVygF",
			"A8WbsPkgZ45VVtyysUN9vV7dtDXiMDRoWk",
			"AFFsHquF53hT3zV7E4SXxdkJK6a8PDEbT8",
			"A4fQ2b984W5BureegkmkMKVP6pJk9ZjnBx",
			"ADkforn8u4HedW4bZJRyK64awpuFGTT4U",
			"AD2SJakmuhbYD5Av6stDjXfdy85xay91jX",
			"A47ouBNuK33c2BX34X5vDJTLuFCAY48az6",
			"APgTWi3qqxyV5p5gFLaNqjWXJ8Ethdyd6R",
			"A4g62ifoqvy7T4NexkEWhrXWRCVQHsPJpx",
			"A9fe7T39aaiTPNAuTeiqU9w8fKhabkNW4y",
			"ACRtG9ndFc4QhH87TABDgi728kwcJQsqTB",
			"AKvceyPsuuuz95nfnFSUT3m5n29eqWDPTG",
			"AFjr4gtAZcukkooUyR4Y1ovnHQCpWRPY3V",
			"AGDyBPJ8EoYKmYXBW8VXcvRusbjMyezdDY",
			"ACuonLZN4hBnwMi9Zh4nkpQ1pfhGu8M9Wy",
			"A5KH3Lgxh82X5DeL5fCEXkRiAEN2Ssi9F2",
			"AJd2SorXSWCwFnafUomDChEpHgh2dAFDEN",
			"A7tdqJorMn7Y1XVB9HKkzSZQx9rCeH3C7Y",
			"AGT9n7TvhmL4QsErNWHxJxgm3v1x61qAot",
			"AH8UB2wUhoypgMqZPmraBrXVrYrDgYbKho",
			"A27V6HZJFDU3cxuqLqgJHHYXbjhscWYuqB",
			"AN3c3U9XHfH2fPJrkjChjHyYRY1fKcwpCp",
			"AFHVknM4svVBjX43sY321GJtV3BK5J69jM",
			"ABV3Lnkxeyzm5hSH59V1zXuUAnegZfkn3w",
			"A4qmut3FCGKW36E9W139RzqYeZ9D9t88dM",
			"AAh86Spdz7DEfT2Lxqwqvi5CwJaWFZAKWG",
			"AMg4oSb3rTyVxYziAdK4YYhZFc6eWEqVyb",
			"AHZNaxutJr8UFUmdN9wSzrCqG69gT62n84",
			"AEqemc18JGPtpwx3WpHRh3WnENWevcKENn",
			"A5eZ2JyF4c4un44jXrSYJpJAJTqDtATUwe",
			"AEqhyVx3Z81jU8P7WEEqeUDC3EvSNYP1Av",
			"AHQHnFZ1vNxCvoUUuW1y5tEp4KkXcwFLWb",
			"AFAgi7ieSkRAUyqSTUkuM5JqFchHbWnWBz",
			"ADGCu1K7Kf7v8EomRVU3JjdUqGVh8m1GiB",
			"A6kZrufK8KgGN5QDXZZXmQtWup8mGBxnaN",
			"A5Xn4Nf8gQjwzcJqrLB6nxKFbcMMSDhBot",
			"ABCsq2jB5up8vSBYMdxMPjtgoHRboWNNE3",
			"A6W2LAhgnrdX25K5M3n8kBydozQVYQPJmr",
			"A7p4MW6Std1QgTrWTydi2mqSeTSc5vG7GB",
			"ADygsSP5DPdXJa7Q7rTMNLSeUtyWQDKZdA",
			"AJH6VCwKniLaaYD3Z1RXk62K3RkTKR36oz",
			"AzFhhgubYymabPMWe1sZavmpAWYcC4zWQ",
			"A5EWKcJ8y2FiiTzaXAH3rXK58DZ3zYjADp",
			"ADHEsxvaG3p8h5n7ikCYDykdyqYWZ8br5A",
			"AJNZmZZxibvPYfRxyGnD4dMJsKHjrfi4Zo",
			"A47zu66DPdFtD2WRd2wxCk7kFzqCkvJYuG",
			"ADv5i9rJyXyP1hxLLE5tGzqMAJV2581ENc",
			"AEX4LzS7178fsExKT1MYVWr8iwdik89uVm",
			"AEe1MnpSKABCtW6uv2FShZMCwG7jEZLpDt",
			"APEr3UW8YQJsVyCfrWDoXEvB1q3YS8FoX7",
			"AN3J83TEJUzzg241t1EJLtUuouvYdqpx15",
			"ADJF9m5RxNQfwgdEm4zPBdGgyMcperdHu9",
			"AKk6XUsyVsDqLQzZzCXWhaFVUUTyMs1P7m",
			"A6yXjgRBsVFePJuDsLZrBD5E32u4VPX5ji"};
	
	public static String[] registerSecret = {"private caution climb veteran write body bird code present caution salad subway",
			"degree almost raccoon join family youth shock assault impact artefact glide canyon",
			"resemble style joy ostrich sort action music drive hope song garment hawk",
			"coast opinion travel jeans current lab poverty dinosaur comic violin spoil sick",
			"child pact reunion sauce agent human leg wear blush gather because gloom",
			"flag female vicious have discover riot rebuild kiwi length undo school dial",
			"anchor plunge hurry online cabbage attitude timber walnut net notable pill move",
			"female pistol air poverty refuse reopen syrup mansion unknown dad fold guard",
			"case large inject common buddy habit analyst initial clown van scout organ",
			"lion little depth cute cruel equal option taxi own coconut taxi sweet",
			"depend pledge trial exit crew melt emotion dune news bonus entire punch",
			"forward critic clump story rebel confirm kingdom leader detect famous metal elite",
			"nest palace ancient girl climb local raven love arrive pioneer riot virtual",
			"rally peanut educate select veteran charge mango admit boss angry wait solid",
			"pepper banana leg grant eye bench battle chief someone purchase slim erode",
			"already double suffer type harsh sight rule era sweet upper gloom icon",
			"cinnamon stuff better draft table curious grocery mutual breeze excuse solar ensure",
			"state cave trick service crash chuckle best recipe fox cram heart hamster",
			"prepare walk armor video scrap rubber dust bottom dice hurry rebuild zero",
			"fortune project melt category radio involve runway ticket nuclear family forum seminar",
			"lab tent use turn budget twin athlete mom baby wood coral detail",
			"enrich monster pattern coyote retire tissue crisp cloth hobby affair pride live",
			"frost slow cheese trophy gloom father finish pole decade drama dutch impulse",
			"puppy museum hint amateur mistake island wonder frown neutral surprise craft steak",
			"action head alert want toddler toe elite hard eight control climb glance",
			"fortune various knee federal crew refuse seven great wisdom hair stove annual",
			"enjoy winter throw sausage siege hungry slender spike remind space style muffin",
			"scatter attitude off marriage air regret claw token program cereal obvious execute",
			"stay ancient tenant pluck tiger inner clinic clever soap observe cycle spice",
			"this mobile divert bomb lucky tongue loan risk brush marble nominee mandate",
			"race simple garbage keen normal ceiling swarm hero hazard pelican program ginger",
			"fruit cheese bridge pony embrace type floor december coach air talk few",
			"extend income glove add kitchen glance bracket about cost owner news bottom"};
}
